channels:
  - conda-forge
  - bioconda
dependencies:
  - amply=0.1.6=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - anyio=4.6.2.post1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312hb553811_5
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.7.31=hc566b99_3
  - aws-c-cal=0.7.4=h40772b6_2
  - aws-c-common=0.9.29=ha44c9a9_0
  - aws-c-compression=0.2.19=h40772b6_2
  - aws-c-event-stream=0.4.3=h453e538_5
  - aws-c-http=0.8.10=h592d179_3
  - aws-c-io=0.14.20=h99e8e40_0
  - aws-c-mqtt=0.10.7=h86759dc_3
  - aws-c-s3=0.6.7=h24045d9_1
  - aws-c-sdkutils=0.1.19=h40772b6_4
  - aws-checksums=0.1.20=h40772b6_1
  - awscli=2.22.3=py312hb401068_0
  - awscrt=0.22.0=py312hd00079b_6
  - babel=2.16.0=pyhd8ed1ab_0
  - bcftools=1.21=h0126a07_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bedtools=2.31.1=hdd9cfa2_2
  - bleach=6.2.0=pyhd8ed1ab_0
  - boto3=1.35.66=pyhd8ed1ab_0
  - botocore=1.35.67=pyge310_1234567_0
  - brotli=1.1.0=h00291cd_2
  - brotli-bin=1.1.0=h00291cd_2
  - brotli-python=1.1.0=py312h5861a67_2
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.3=hf13058a_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py312hf857d28_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - coin-or-cbc=2.10.12=h26cd4a2_1
  - coin-or-cgl=0.60.9=h5c63661_0
  - coin-or-clp=1.17.10=hf05e7e8_0
  - coin-or-osi=0.108.11=h8c189bd_1
  - coin-or-utils=2.11.12=h95c8798_1
  - coincbc=2.10.12=1_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - coloredlogs=15.0.1=pyhd8ed1ab_3
  - comm=0.2.2=pyhd8ed1ab_0
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.3.1=py312hc47a885_0
  - cryptography=43.0.1=py312h840e0bc_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - datrie=0.8.2=py312hb553811_8
  - debugpy=1.8.9=py312haafddd8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distro=1.8.0=pyhd8ed1ab_0
  - docutils=0.17.1=py312hb401068_5
  - dpath=2.2.0=pyha770c72_0
  - eido=0.2.4=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fonttools=4.55.0=py312h3520af0_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h60636b9_2
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - gsl=2.7=h93259b0_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - htslib=1.21=hec81eee_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - humanfriendly=10.0=pyhd81877a_7
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_0
  - immutables=0.21=py312hb553811_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.17.2=pyh31c8845_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhff2d567_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - json5=0.9.28=pyhff2d567_0
  - jsonpointer=3.0.0=py312hb401068_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.3.1=pyhff2d567_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py312hc5c4d5f_0
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.16=ha2f27b4_0
  - lerc=4.0.0=hb486fe8_0
  - libblas=3.9.0=25_osx64_openblas
  - libbrotlicommon=1.1.0=h00291cd_2
  - libbrotlidec=1.1.0=h00291cd_2
  - libbrotlienc=1.1.0=h00291cd_2
  - libcblas=3.9.0=25_osx64_openblas
  - libcurl=8.10.1=h58e7537_0
  - libcxx=19.1.4=hf95d169_0
  - libdeflate=1.21=hfdf4475_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=h10d778d_2
  - libexpat=2.6.4=h240833e_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libjpeg-turbo=3.0.0=h0dc2134_1
  - liblapack=3.9.0=25_osx64_openblas
  - liblapacke=3.9.0=25_osx64_openblas
  - libnghttp2=1.64.0=hc7306c3_0
  - libopenblas=0.3.28=openmp_hbf64a52_1
  - libpng=1.6.44=h4b8f8c9_0
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.47.0=h2f8c449_1
  - libssh2=1.11.0=hd019ec5_0
  - libtiff=4.7.0=h5f227bf_0
  - libwebp-base=1.4.0=h10d778d_0
  - libxcb=1.17.0=hf1f96e2_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=19.1.4=ha54dae1_0
  - logmuse=0.2.8=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312hbe3f5e4_0
  - matplotlib-base=3.9.2=py312h30cc4df_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=hf036a51_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=2.1.3=py312hfc93d17_0
  - openjpeg=2.5.2=h7310d3a_0
  - openssl=3.5.1=hc426f3f_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.2=pyhff2d567_1
  - pandas=2.2.3=py312h98e817e_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=1.0.1=pyhff2d567_0
  - pephubclient=0.4.4=pyhd8ed1ab_0
  - peppy=0.40.7=pyhd8ed1ab_1
  - perl=5.32.1=7_h10d778d_perl5
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=11.0.0=py312h66fe14f_0
  - pip=24.3.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - plac=1.4.3=pyhd8ed1ab_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=6.1.0=py312h3d0f464_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.8.0=py312hb401068_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybedtools=0.10.0=py312ha99f805_2
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.10.2=pyh3cfb1c2_0
  - pydantic-core=2.27.1=py312h0d0de52_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyobjc-core=10.3.1=py312hab44e94_1
  - pyobjc-framework-cocoa=10.3.1=py312hab44e94_1
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pysam=0.22.1=py312h7023193_2
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.3.4=pyhd8ed1ab_0
  - python=3.12.7=h8f8b54e_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312hb553811_1
  - pyzmq=26.2.0=py312h1060d5c_3
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h9e318b2_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.9.4=pyhd8ed1ab_0
  - rpds-py=0.21.0=py312h0d0de52_0
  - ruamel.yaml=0.17.17=py312h3d0f464_3
  - ruamel.yaml.clib=0.2.8=py312h3d0f464_1
  - s3path=0.5.8=pyhd8ed1ab_0
  - s3transfer=0.10.4=pyhd8ed1ab_0
  - samtools=1.21=h94387ee_0
  - scipy=1.14.1=py312h888eae2_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.3=pyh31c8845_0
  - setuptools=75.6.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - slack-sdk=3.33.4=pyhff2d567_1
  - slack_sdk=3.33.4=hff2d567_1
  - smart_open=7.0.5=pyhd8ed1ab_1
  - smmap=5.0.0=pyhd8ed1ab_0
  - snakemake=8.25.4=hdfd78af_0
  - snakemake-interface-common=1.17.4=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.3.2=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.1.0=pyhdfd78af_0
  - snakemake-interface-storage-plugins=3.3.0=pyhdfd78af_0
  - snakemake-minimal=8.25.4=pyhdfd78af_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.4=py312h3a11e2b_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - terminado=0.18.1=pyh31c8845_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - tomli=2.1.0=pyhff2d567_0
  - tornado=6.4.1=py312hb553811_1
  - tqdm=4.67.0=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typer=0.14.0=pyhd8ed1ab_0
  - typer-slim=0.14.0=pyhd8ed1ab_0
  - typer-slim-standard=0.14.0=hd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024b=hc8b5060_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - unicodedata2=15.1.0=py312h3d0f464_1
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=1.26.19=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.45.0=pyhd8ed1ab_0
  - wrapt=1.16.0=py312hb553811_1
  - xorg-libxau=1.0.11=h00291cd_1
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - yte=1.5.4=pyha770c72_0
  - zeromq=4.3.5=h7130eaa_7
  - zipp=3.21.0=pyhd8ed1ab_0
  - zstd=1.5.6=h915ae27_0
  - pip:
      - motif-scraper==1.0.3
      - pyfaidx==0.8.1.3
      - regex==2024.11.6
